# Generated by Django 4.0.1 on 2022-07-11 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daitech', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk']},
        ),
    ]
