# Generated by Django 4.0.1 on 2022-07-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daitech', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
